// Array of quotes
const quotes = [
    "Life is what happens when you're busy making other plans.",
    "The purpose of our lives is to be happy.",
    "Get busy living or get busy dying. — Stephen King",
    "You only live once, but if you do it right, once is enough.",
    "In the end, it's not the years in your life that count, it's the life in your years.",
    "Life is short, and it's up to you to make it sweet.",
    "Difficulties in life are intended to make us better, not bitter.",
    "To live is the rarest thing in the world. Most people exist, that is all.",
    "Life is really simple, but we insist on making it complicated.",
    "Life is a journey that must be traveled no matter how bad the roads and accommodations.",
    "Life is 10% what happens to us and 90% how we react to it.",
    "The longer I live, the more I realize the impact of attitude on life.",
    "Life is not about finding yourself. Life is about creating yourself.",
    "Believe that life is worth living and your belief will help create the fact.",
    "Keep calm and carry on.",
    "Do not take life too seriously. You will never get out of it alive.",
    "Good friends, good books, and a sleepy conscience: this is the ideal life.",
    "The good life is one inspired by love and guided by knowledge.",
    "Life itself is the most wonderful fairy tale.",
    "A man who dares to waste one hour of time has not discovered the value of life.",
    "The best way to predict your future is to create it.",
    "The meaning of life is to find your gift. The purpose of life is to give it away.",
    "Life isn’t about waiting for the storm to pass, it’s about learning to dance in the rain.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "Every moment is a fresh beginning.",
    "Everything you’ve ever wanted is on the other side of fear.",
    "The only impossible journey is the one you never begin.",
    "Life is like riding a bicycle. To keep your balance, you must keep moving.",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
    "The unexamined life is not worth living.",
    "Change your thoughts and you change your world.",
    "The purpose of life is to believe, to hope, and to strive.",
    "Live in the sunshine, swim the sea, drink the wild air.",
    "Every man dies. Not every man really lives.",
    "Life is a daring adventure or nothing at all.",
    "You have within you right now, everything you need to deal with whatever the world can throw at you.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    "Don't count the days, make the days count.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Live each day as if your life had just begun.",
    "Do not let making a living prevent you from making a life.",
    "Act as if what you do makes a difference. It does.",
    "Don’t be pushed by your problems. Be led by your dreams.",
    "Where there is love, there is life.",
    "Life is a succession of lessons which must be lived to be understood.",
    "Success is how high you bounce when you hit bottom.",
    "Only a life lived for others is a life worthwhile.",
    "Life is made of ever so many partings welded together.",
    "Do what you can, with what you have, where you are.",
    "May you live all the days of your life.",
    "Life is too important to be taken seriously.",
    "Life isn't about finding yourself. Life is about creating yourself.",
    "The secret to life is to love who you are — warts and all.",
    "Your time is limited, don't waste it living someone else's life.",
    "To live is the rarest thing in the world. Most people exist, that is all.",
    "Life is either a daring adventure or nothing at all.",
    "The greatest use of a life is to spend it on something that will outlast it.",
    "Not how long, but how well you have lived is the main thing.",
    "Life is a mirror and will reflect back to the thinker what he thinks into it.",
    "Life is a series of natural and spontaneous changes.",
    "The only way to do great work is to love what you do.",
    "Life is short, and it is here to be lived.",
    "Good friends, good books, and a sleepy conscience: this is the ideal life.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "Life shrinks or expands in proportion to one's courage.",
    "Don't cry because it's over, smile because it happened.",
    "Live as if you were to die tomorrow. Learn as if you were to live forever.",
    "It does not matter how slowly you go, as long as you do not stop.",
    "Do not watch the clock; do what it does. Keep going.",
    "We do not remember days, we remember moments.",
    "Life is short, and it's up to you to make it sweet.",
    "Live in the sunshine, swim the sea, drink the wild air.",
    "Don't watch the clock; do what it does. Keep going.",
    "Act as if what you do makes a difference. It does.",
    "The secret of success is to do the common things uncommonly well.",
    "Success is not in what you have, but who you are.",
    "You are enough just as you are.",
    "Life is not about finding yourself. Life is about creating yourself.",
    "In three words I can sum up everything I've learned about life: it goes on.",
    "The good life is a process, not a state of being. It is a direction, not a destination.",
    "Life is 10% what happens to us and 90% how we react to it.",
    "Life is like riding a bicycle. To keep your balance, you must keep moving.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "Your life does not get better by chance, it gets better by change.",
    "The unexamined life is not worth living.",
    "Don't count the days, make the days count.",
    "Love is composed of a single soul inhabiting two bodies. — Aristotle",
"To love and be loved is to feel the sun from both sides.— David Viscott",
"The best thing to hold onto in life is each other. — Audrey Hepburn",
"Love is not something you find. Love is something that finds you. — Loretta Young",
"Where there is love, there is life.— Mahatma Gandhi",
"Being deeply loved by someone gives you strength while loving someone deeply gives you courage. — Lao Tzu",
"Love is a friendship set to music.— Joseph Campbell",
"Love doesn't make the world go 'round. Love is what makes the ride worthwhile. — Franklin P. Jones",
"In the end, we discover that to love and let go can be the same thing.— Jack Kornfield",
"The greatest thing you'll ever learn is just to love and be loved in return.— Nat King Cole",
"The way to love anything is to realize that it may be lost.— Gilbert K. Chesterton",
"To love is nothing. To be loved is something. But to love and be loved, that’s everything. — T. Tolis",
"Love is the only force capable of transforming an enemy into a friend.— Martin Luther King Jr.",
"Love is a canvas furnished by Nature and embroidered by imagination. — Voltaire",
"We are shaped and fashioned by what we love. — Johann Wolfgang von Goethe",
"The best proof of love is trust. — Joyce Brothers",
"There is no remedy for love but to love more.— Henry David Thoreau",
"Love is a promise; love is a souvenir, once given never forgotten, never let it disappear. — John Lennon",
"Love is a game that two can play and both win. — Eva Gabor",
"To love is to burn, to be on fire. — Jane Austen",
"The heart has its reasons which reason knows not.— Blaise Pascal",
"Love is the flower; you've got to let it grow. — John Lennon",
"Love is like the wind, you can't see it but you can feel it. — Nicholas Sparks",
"True love stories never have endings. — Richard Bach",
"Love is not what you say. Love is what you do. — Unknown",
"The only thing we never get enough of is love; and the only thing we never give enough of is love. — Henry Miller",
"You come to love not by finding the perfect person, but by seeing an imperfect person perfectly. — Sam Keen",
"Love is an irresistible desire to be irresistibly desired. — Robert Frost",
"Love is a better teacher than duty. — Albert Einstein",
"To be brave is to love unconditionally without expecting anything in return.— Madonna",
"Love is when you meet someone who tells you something new about yourself. — Andre Breton",
"Love does not dominate; it cultivates. — Johann Wolfgang von Goethe",
"To love is to receive a glimpse of heaven. — Karen Sunde",
"A life lived in love will never be dull. — Leo Buscaglia",
"Love cures people—both the ones who give it and the ones who receive it. — Karl A. Menninger",
"Love is a choice you make from moment to moment. — Barbara De Angelis",
"To love oneself is the beginning of a lifelong romance. — Oscar Wilde",
"Love is not about possession. Love is about appreciation. — Osho",
"Love is when the other person's happiness is more important than your own. — H. Jackson Brown Jr.",
"Love is the whole thing. We are only pieces. — Rumi",
"Love is a smoke made with the fume of sighs. — William Shakespeare",
"The first duty of love is to listen. — Paul Tillich",
"Love is like war: easy to begin but very hard to stop. — H. L. Mencken",
"Love is what you’ve been through with somebody. — James Thurber",
"If I know what love is, it is because of you. — Herman Hesse",
"Love doesn't just sit there, like a stone; it has to be made, like bread, remade all the time, made new. — Ursula K. Le Guin",
"Love is not love until love's vulnerable. — Theodore Roethke",
"Love is the greatest refreshment in life. — Pablo Picasso",
"Love is the master key that opens the gates of happiness. — Oliver Wendell Holmes",
"We loved with a love that was more than love. — Edgar Allan Poe",
"A loving heart is the truest wisdom. — Charles Dickens",
"Love is the bridge between you and everything. — Rumi",
"Love will find a way through paths where wolves fear to prey. — Lord Byron",
"Love makes your soul crawl out from its hiding place. — Zora Neale Hurston",
"Love is a fire. But whether it is going to warm your hearth or burn down your house, you can never tell. — Joan Crawford",
"Love is a fruit in season at all times, and within reach of every hand. — Mother Teresa",
"Love is the magician that pulls man out of his own hat. — Ben Hecht",
"Love is a great beautifier. — Louisa May Alcott",
"Love's greatest gift is its ability to make everything it touches sacred. — Barbara De Angelis",
"To love is to act. — Victor Hugo",
"Love is when you look into someone's eyes and see everything you need. — Unknown",
"Love takes off masks that we fear we cannot live without and know we cannot live within. — James Baldwin",
"Love is the beauty of the soul. — Saint Augustine",
"We are most alive when we're in love. — John Updike",
"Love is the absence of judgment. — Dalai Lama",
"Love is a friendship that has caught fire. — Ann Landers",
"Love is like a virus. It can happen to anybody at any time. — Maya Angelou",
"Love is not only something you feel, it is something you do. — David Wilkerson",
"Love is the ultimate expression of the will to live. — Tom Wolfe",
"Love is a better master than duty. — Albert Einstein",
"Love is like the sun coming out of the clouds and warming your soul. — Unknown",
"The heart wants what it wants. There's no logic to these things. — Woody Allen",
"The greatest happiness of life is the conviction that we are loved. — Victor Hugo",
"Love is an endless act of forgiveness. Forgiveness is the key to action and freedom. — Maya Angelou",,
"Love is a friendship set to music. — Joseph Campbell",
"Love is the poetry of the senses. — Honore de Balzac",
"Love is a choice you make every day. — Gary Chapman",
"There is no charm equal to tenderness of heart. — Jane Austen",
"Love is not a matter of counting the years, but making the years count. — Michelle St. Amand",
"In dreams and in love, there are no impossibilities. — Janos Arany",
"Love is what makes the ride worthwhile. — Franklin P. Jones",
"To love and be loved is to feel the sun from both sides. — David Viscott",
"You can't blame gravity for falling in love. — Albert Einstein",
"Love is the greatest adventure. —Valens",
"Education is the most powerful weapon which you can use to change the world. — Nelson Mandela",  
"The roots of education are bitter, but the fruit is sweet. — Aristotle ", 
"Education is not preparation for life; education is life itself. — John Dewey",  
"The only person who is educated is the one who has learned how to learn and change. — Carl Rogers",  
"An investment in knowledge pays the best interest. — Benjamin Franklin ", 
"Education is the passport to the future, for tomorrow belongs to those who prepare for it today. — Malcolm X  ",
"The beautiful thing about learning is that no one can take it away from you. — B.B. King",  
"Education is not the filling of a pail, but the lighting of a fire. — W.B. Yeats ", 
"Education is the key to unlocking the world, a passport to freedom.— Oprah Winfrey",  
"The purpose of education is to replace an empty mind with an open one. — Malcolm Forbes ", 
"It is the mark of an educated mind to be able to entertain a thought without accepting it. — Aristotle",  
"A good education is a foundation for a better future. — Elizabeth Warren",  
"Education is simply the soul of a society as it passes from one generation to another.— G.K. Chesterton",  
"The more you learn, the more you earn. — Warren Buffett ", 
"Education is the movement from darkness to light. — Allan Bloom",  
"Education is what remains after one has forgotten what one has learned in school. — Albert Einstein ", 
"The goal of education is the advancement of knowledge and the dissemination of truth. — John F. Kennedy",  
"The greatest education in the world is watching the masters at work. — Michael Jackson",  
"The mind is not a vessel to be filled, but a fire to be kindled. — Plutarch",  
"The secret of education lies in respecting the pupil. — Ralph Waldo Emerson",  
"Develop a passion for learning. If you do, you will never cease to grow. — Anthony J. D'Angelo " ,
"Live as if you were to die tomorrow. Learn as if you were to live forever. — Mahatma Gandhi ", 
"Learning never exhausts the mind. — Leonardo da Vinci", 
"Education is a better safeguard of liberty than a standing army. — Edward Everett",  
"Knowledge will bring you the opportunity to make a difference. — Claire Fagin" , 
"Teachers can open the door, but you must enter it yourself. — Chinese Proverb",  
"The purpose of education is to make minds, not careers. — William Deresiewicz ", 
"Education begins the gentleman, but reading, good company, and reflection must finish him. — John Locke ", 
"Learning is the only thing the mind never exhausts, never fears, and never regrets. — Leonardo da Vinci",  
"A child without education is like a bird without wings. — Tibetan Proverb",  
"Education's purpose is to replace an empty mind with an open one. — Malcolm Forbes",  
"To educate a person in the mind but not in morals is to educate a menace to society. — Theodore Roosevelt",  
"Intelligence plus character—that is the goal of true education.— Martin Luther King Jr.",  
"A well-educated mind will always have more questions than answers. — Helen Keller ", 
"The only thing that interferes with my learning is my education. — Albert Einstein",  
"Education breeds confidence. Confidence breeds hope. Hope breeds peace. — Confucius",  
"Education is learning what you didn’t even know you didn’t know. — Daniel J. Boorstin ", 
"An investment in knowledge always pays the best interest. — Benjamin Franklin",  
"Education is not just about passing exams. It's about understanding the world and preparing for the future. —valens", 
"Education is the foundation upon which we build our future. — Christine Gregoire ", 
"The best teachers are those who show you where to look but don’t tell you what to see. — Alexandra K. Trenfor",  
"Education is a journey, not a destination. — Unknown",  
"The more you know, the more you realize how much you don't know. — Aristotle",  
"Education is the kindling of a flame, not the filling of a vessel. — Socrates",  
"He who opens a school door, closes a prison. — Victor Hugo",  
"Education must not simply teach work—it must teach life. — W.E.B. Du Bois ", 
"Education is a progressive discovery of our own ignorance. — Will Durant  ",
"What sculpture is to a block of marble, education is to the human soul. — Joseph Addison",  
"You are always a student, never a master. You have to keep moving forward.— Conrad Hall  ",
"The aim of education is the knowledge, not of facts, but of values.— William S. Burroughs",  
"Educating the mind without educating the heart is no education at all. — Aristotle", 
"The best education I have ever received was through travel. — Lisa Ling  ",
"Education is a precondition to survival in America today. — Marian Wright Edelman ", 
"The more that you read, the more things you will know. The more that you learn, the more places you’ll go. — Dr. Seuss  ",
"Education is the mother of leadership. — Wendell Willkie",  
"Education is not the learning of facts, but the training of the mind to think. — Albert Einstein",  
"The future belongs to those who believe in the beauty of their dreams. — Eleanor Roosevelt",  
"A good education is a foundation for a better future. — Elizabeth Warren ", 
"The educated differ from the uneducated as much as the living differ from the dead. — Aristotle",  
"The object of education is to prepare the young to educate themselves throughout their lives. — Robert M. Hutchins ", 
"Education is for improving the lives of others and for leaving your community and world better than you found it. — Marian Wright Edelman",  
"The more you learn, the more places you'll go. — Dr. Seuss ", 
"Education is our passport to the future, for tomorrow belongs to the people who prepare for it today. — Malcolm X ", 
"Learning is a treasure that will follow its owner everywhere. — Chinese Proverb ", 
"A teacher affects eternity; he can never tell where his influence stops. — Henry Adams",  
"The whole purpose of education is to turn mirrors into windows. — Sydney J. Harris  ",
"Education is the door to freedom, democracy, and development. — Nelson Mandela  ",
"The essence of knowledge is having it, to apply it; not having it, to confess your ignorance. — Confucius ", 
"Education should be exercise; it has become massage. — Martin H. Fischer ", 
"Education is the foundation upon which we build our future.— Christine Gregoire  ",
"Learning is a lifelong process of keeping abreast of change. — Peter Drucker",  
"The highest result of education is tolerance. — Helen Keller  ",
"You educate a man; you educate a man. You educate a woman; you educate a generation. — Brigham Young ", 
"Formal education will make you a living; self-education will make you a fortune. — Jim Rohn  ",
"It is the supreme art of the teacher to awaken joy in creative expression and knowledge. — Albert Einstein  ",
"Education is not the answer to the question. Education is the means to the answer to all questions.— William Allin", 
"Success usually comes to those who are too busy to be looking for it. — Henry David Thoreau  ",
"The secret of business is to know something that nobody else knows. — Aristotle Onassis ", 
"Opportunities don't happen. You create them. — Chris Grosser  ",
"Success in business requires training, discipline, and hard work. — David Rockefeller  ",
"The best way to predict the future is to create it. — Peter Drucker  ",
"Your most unhappy customers are your greatest source of learning. — Bill Gates ", 
"The only way to do great work is to love what you do. — Steve Jobs  ",
"Chase the vision, not the money; the money will end up following you. — Tony Hsieh  ",
"In business, the competition will bite you if you keep running; if you stand still, they will swallow you. — Victor Kiam ", 
"Business opportunities are like buses, there’s always another one coming. — Richard Branson ", 
"A satisfied customer is the best business strategy of all. — Michael LeBoeuf ", 
"To succeed in business, it’s not what you know, it’s who you know.— Anonymous  ",
"Business is more exciting than any game. — Lord Beaverbrook  ",
"It’s not about ideas. It’s about making ideas happen. — Scott Belsky  ",
"Success in business is about people, relationships, and strategy. — Robin Sharma  ",
"The purpose of business is to create and keep a customer.— Peter Drucker  ",
"Do not be embarrassed by your failures, learn from them and start again. — Richard Branson  ",
"Your time is limited, so don’t waste it living someone else’s life. — Steve Jobs  ",
"Great things in business are never done by one person. They’re done by a team of people. — Steve Jobs  ",
"Business is a game, played for fantastic stakes, and you're in competition with experts. If you want to win, you have to learn to be a master of the game. — Sidney Sheldon ", 
"Innovation distinguishes between a leader and a follower.— Steve Jobs ",
"The way to get started is to quit talking and begin doing.— Walt Disney ", 
"Every problem is a gift—without problems, we would not grow. — Anthony Robbins  ",
"I find that the harder I work, the more luck I seem to have. — Thomas Jefferson  ",
"The entrepreneur always searches for change, responds to it, and exploits it as an opportunity. — Peter Drucker ", 
"There’s no shortage of remarkable ideas, what’s missing is the will to execute them. — Seth Godin ",
"Don’t be afraid to give up the good to go for the great. — John D. Rockefeller  ",
"The only limits to our realization of tomorrow will be our doubts of today. — Franklin D. Roosevelt ", 
"Business has only two functions – marketing and innovation. — Peter Drucker ", 
"In business, one has no friends, only correspondents. — Alexandre Dumas",  
"If you’re not a risk taker, you should get the hell out of business. — Ray Kroc ", 
"Don’t wait for the right opportunity: create it. — George Bernard Shaw  ","om being perfect. — Adam Osborne ", 
"A big business starts small. — Richard Branson  ",
"The successful warrior is the average man, with laser-like focus.— Bruce Lee  ",
"Do not let the fear of losing be greater than the excitement of winning. — Robert Kiyosaki",  
"Success isn’t just about what you accomplish in your life, it’s about what you inspire others to do. — Anonymous ", 
"If you really look closely, most overnight successes took a long time. — Steve Jobs  ",
"The first step toward success is taken when you refuse to be a captive of the environment in which you first find yourself. — Mark Caine",  
"The best way to predict the future is to invent it. — Alan Kay ", 
"Quality is not an act, it is a habit. — Aristotle ", 
"The biggest risk is not taking any risk. — Mark Zuckerberg",  
"If you are not embarrassed by the first version of your product, you’ve launched too late. — Reid Hoffman ", 
"When something is important enough, you do it even if the odds are not in your favor. — Elon Musk  ",
"The secret to successful hiring is this: look for the people who want to change the world. — Marc Benioff ", 
"The successful man is the one who finds out what is the matter with his business before his competitors do. — Roy L. Smith ", 
"Timing, perseverance, and ten years of trying will eventually make you look like an overnight success. — Biz Stone ", 
"A business has to be involving, it has to be fun, and it has to exercise your creative instincts. — Richard Branson",  
"You miss 100% of the shots you don’t take. — Wayne Gretzky  ",
"Always deliver more than expected.— Larry Page ", 
"Business opportunities are like buses, there's always another one coming. — Richard Branson  ",
"A goal without a timeline is just a dream.— Robert Herjavec ",
"The road to success and the road to failure are almost exactly the same. — Colin R. Davis ",
"If you don't drive your business, you will be driven out of business. — B.C. Forbes  ",
"You don’t build a business. You build people, then people build the business. — Zig Ziglar  ",
"Success is not final; failure is not fatal: It is the courage to continue that counts.— Winston S. Churchill ", 
"It’s not about ideas. It’s about making ideas happen. — Scott Belsky  ",
"You have to believe in yourself when no one else does – that makes you a winner right there. — Venus Williams  ",
"Business is all about relationships…how well you build them determines how well they build your business. — Brad Sugars  ",
"A satisfied customer is the best business strategy of all. — Michael LeBoeuf  ",
"Efforts and courage are not enough without purpose and direction. — John F. Kennedy  ",
"Stay self-funded as long as possible. — Garrett Camp  ",
"The goal of a successful entrepreneur is not to build a great company, but to build a great team. — Kevin O’Leary  ",
"In the end, a vision without the ability to execute it is probably a hallucination.— Steve Case  ",
"Action is the foundational key to all success. — Pablo Picasso  ",
"The difference between winning and losing is most often not quitting. — Walt Disney",  
"Success is walking from failure to failure with no loss of enthusiasm. — Winston Churchill  ",
"The only place where success comes before work is in the dictionary. — Vidal Sassoon  ",
"To succeed in business, you need to be original, but you also need to understand what your customer wants. — Peter Thiel ", 
"Price is what you pay. Value is what you get. — Warren Buffett ",
"Business is the art of extracting money from another man’s pocket without resorting to violence. — Max Amsterdam  ",
"Hire character. Train skill. — Peter Schutz  ",
"The key to success is to start before you are ready. — Marie Forleo ", 
"Success is often achieved by those who don’t know that failure is inevitable. — Coco Chanel ",
"Efforts and courage are not enough without purpose and direction. — John F. Kennedy  ",
"In business, the rearview mirror is always clearer than the windshield. — Warren Buffett  ",
"If you don't innovate, you die.— Tom Peters  ",
"The secret of getting ahead is getting started. — Mark Twain ", 
"Don’t sit down and wait for the opportunities to come. Get up and make them. — Madam C.J. Walker ", 
"If people like you, they'll listen to you, but if they trust you, they'll do business with you. — Zig Ziglar ", 
"The only way around is through. — Robert Frost",  
"You only have to do a few things right in your life so long as you don’t do too many things wrong. — Warren Buffett ", 
"Innovation is saying no to a thousand things. — Steve Jobs  ",
  ];
  
  const usedIndexes = new Set();
  
  const quoteElement = document.getElementById("quote");
  
  function generateQuote() {
    while (true) {
      const randomIndex = Math.floor(Math.random() * quotes.length); // Generate a random index
      if (usedIndexes.has(randomIndex)) {
      }
      const quote = quotes[randomIndex]; 
      quoteElement.innerHTML = quote; 
      usedIndexes.add(randomIndex); 
      break; 
    }
  
    if (usedIndexes.size === quotes.length) {
      usedIndexes.clear();
    }
  }
  
  document.getElementById("generateButton").addEventListener("click", generateQuote);

  var currentDate= new Date();
  var formattedDate=currentDate.toLocaleDateString('en-US',{
    weekday:'long',
    year:'numeric',
    month:'long',
    day:'numeric'

  });
  document.getElementById('footer').innerHTML=currentDate;